sudo: false

cache:
    apt: true
    directories:
    - "$HOME/.cache/pip"
    - "$HOME/.ccache"
    - "$HOME/.pip-cache"

dist: trusty

language: python

notifications:
    email: false

matrix:
    include:
    - python: '2.7'
      env: TOXENV="flake8"
    - python: '2.7'
      env: TOXENV="docs"
    - python: '2.7'
      env: TOXENV="py27-linux"
    - python: '3.5'
      env: TOXENV="py35-linux"
    - python: '3.6'
      env: TOXENV="py36-linux"

install:
    - pip install tox
    - pip install python-coveralls

script:
    - tox -vv

after_success:
    - coveralls

deploy:
  - provider: pages
    local-dir: doc/build
    skip-cleanup: true
    github-token: $gh_pages
    keep-history: true
    on:
      branch: master
      condition: $TOXENV = "docs"
  - provider: pypi
    user: markroxor
    password:
        secure: Y6hXWaOQWx7OtPScGL/YtolEvtXnE5f8gyIHgjNyEeqkJIwAmq9Ifxkv+8DKMNCHIqayj3ttp8lSFsK0eTMrClIhIMw740ODF0eeGyKwoT9XupFDl1asQx7Ts6j0f1h7MliY4zS+5e7rMDXdWXPjXC5zScDJWacBcsXWMvRe7uaQIirIazTJwaysqRc4RKRHwJnZhqeUaMycpp/gBHIw1hyFvtSTQ4GYeYDfGBT9knAYo4GyLxQ1+omzeNRYTuDd22LSV086LbbCK7xeYkkw188HH8AGjFo91AlIVlgTJgTePl9Ss4PZQt0MZS7D9110L0dCXNsCWBe4JqA6EeuyQkkc6SPdErMbC7tJKmBcBt4kwAn/XC4flzLpgei6EeGJtVLOgn0QM5RMyZPgOwTMeH/J7IH2p6a0KRBwxDPUo3OwvxRiRqZtnkUAE+QWo09xIAjg1d6cBlT6Aw+/oSgTnLI1GaqoiDBOEh4ygiRIP4rDw5VvPoKnxhz/GNHcIfHIT9FpFRp+xbTkzfWaUhhIKGliZiOYB16zilXChAWiUAQkrEujDY851Q0AxERIozc1o4qPh6Zoh6rhKorTAnK/qNcGAT48FstcLBYb9GmeBrYrTXpiS6BxianlZh8YqD8vD8mZ+RsMFIH1GRWBa4sGzQXUhmxqtxpBr94sNNyIT1s=
    distributions: sdist bdist_wheel
    on:
      tags: true
